version: "3.8"

services:

  # Backend API
  face-detection-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/face-detection-api
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/face-detection-docker
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/face-detection-api
    # networks:
    #   - proxynet
  
  # Postgres
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: face-detection-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
     - "5432:5432"

# networks:
#   proxynet:
#     external:
#       name: custom_network